//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCRUDEF.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int Id { get; set; }
        [Display(Name = "Please Enter the Employee Name")]
        [Required(ErrorMessage = "Name cannot be Empty")]
        [MaxLength(50, ErrorMessage = "Name should not be more than 50 char")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Joining Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> JoinDate { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email Address")]
        public string Email { get; set; }

        [Required]
        [Phone]
        [MinLength(2, ErrorMessage = " Phone Number should more than 2 digit")]
        [MaxLength(11, ErrorMessage = "Phone Number should not be more than 11 digit")]
        [Display(Name = "Cell Phone Number")]
        public string Cell { get; set; }


        [Required]
        [Range(1000, 60000, ErrorMessage = "salary should between 1000 to 60000 range")]
        [Display(Name = "Salary")]
        public Nullable<double> Salary { get; set; }

        [Required]
        public string Designation { get; set; }
    }
}
