//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labtask4CRUDEFF.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int Id { get; set; }

        [Display(Name = "Student Name")]
        [Required(ErrorMessage = "Name cannot be Empty")]
        [MaxLength(50, ErrorMessage = "Not more than 50 alphabets")]
        public string Name { get; set; }

        [Display(Name = "Student CGPA")]
        [Required(ErrorMessage = "CGPA cannot be Empty")]
        public Nullable<double> Cgpa { get; set; }

        [Display(Name = "Addmission Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Date cannot be Empty")]
        public Nullable<System.DateTime> AddmissionDate { get; set; }

        [Display(Name = "Student Department")]
        [Required(ErrorMessage = "Department cannot be Empty")]
        public int DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
